# Generated by Django 3.2.8 on 2021-10-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='type_cargo',
            field=models.CharField(choices=[('rf', 'rf'), ('el', 'el'), ('ol', 'ol'), ('mc', 'mc')], default='choose_type', max_length=20),
        ),
    ]
