# Generated by Django 3.2.8 on 2021-10-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cargo_type_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='duration',
            field=models.CharField(choices=[('30 days', 30), ('60 days', 60), ('90 days', 90), ('180 days', 180), ('1yr-above', 365)], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='type_cargo',
            field=models.CharField(choices=[('refrigerated', 'refrigerated'), ('electronics', 'electronics'), ('other_luggage', 'other_luggage'), ('machinery', 'machinery')], default='choose_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.CharField(choices=[('0-100kgs', 1), ('101-500kgs', 2), ('501-1000kgs', 3), ('1000 and above', 4)], default='weight', max_length=20),
        ),
    ]
