# Generated by Django 3.2.8 on 2021-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cargo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
